# This is the senitmental file where we will train the llm to different - different emotions like joy anger and etc.

In [1]:
import pandas as pd
books = pd.read_csv("books_with_categories.csv")
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,simple_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critic...,Fiction
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web - A Novel,9780002261982 A new 'Christie for Christmas' ...,Fiction
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroin...",Fiction
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lo...,Nonfiction
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. L...",Nonfiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6139,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a m...,Nonfiction
6140,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Pass...,Fiction
6141,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that - Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless...,Nonfiction
6142,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition ...,Nonfiction
6143,9789042003408,9042003405,'I'm Telling You Stories',Helena Grice;Tim Woods,Literary Criticism,http://books.google.com/books/content?id=2lVyR...,This is a jubilant and rewarding collection of...,1998.0,3.70,136.0,10.0,'I'm Telling You Stories' - Jeanette Winterson...,9789042003408 This is a jubilant and rewardin...,Nonfiction

In [2]:
# we will be treating the sentimental analysis as a text classification problem. We will use hugging face model for this aswell.
from transformers import pipeline

classifier = pipeline(task="text-classification", model="SamLowe/roberta-base-go_emotions", top_k=None, device="mps")

sentences = ["I think i have crush on someone}"]

model_outputs = classifier(sentences)
print(model_outputs[0])
# produces a list of dicts for each of the labels

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

[{'label': 'love', 'score': 0.8801727890968323}, {'label': 'neutral', 'score': 0.05702304467558861}, {'label': 'approval', 'score': 0.026206491515040398}, {'label': 'admiration', 'score': 0.009462453424930573}, {'label': 'realization', 'score': 0.007975976914167404}, {'label': 'desire', 'score': 0.006757383234798908}, {'label': 'optimism', 'score': 0.006111984606832266}, {'label': 'confusion', 'score': 0.0048943618312478065}, {'label': 'annoyance', 'score': 0.0043005309998989105}, {'label': 'joy', 'score': 0.004241832997649908}, {'label': 'excitement', 'score': 0.004124095663428307}, {'label': 'disappointment', 'score': 0.0037450932431966066}, {'label': 'amusement', 'score': 0.0035579618997871876}, {'label': 'disapproval', 'score': 0.0035065363626927137}, {'label': 'anger', 'score': 0.0034942827187478542}, {'label': 'caring', 'score': 0.003376362146809697}, {'label': 'disgust', 'score': 0.0029835791792720556}, {'label': 'sadness', 'score': 0.0026831398718059063}, {'label': 'curiosity', 'score': 0.0025320504792034626}, {'label': 'surprise', 'score': 0.0019190182210877538}, {'label': 'remorse', 'score': 0.00164764653891325}, {'label': 'gratitude', 'score': 0.001460776082240045}, {'label': 'fear', 'score': 0.0014226320199668407}, {'label': 'embarrassment', 'score': 0.0009217457845807076}, {'label': 'nervousness', 'score': 0.0007041103672236204}, {'label': 'grief', 'score': 0.00037010846426710486}, {'label': 'relief', 'score': 0.00028298728284426033}, {'label': 'pride', 'score': 0.000276834616670385}]

In [3]:
# books["description"][5]

In [4]:
classifier(books["description"][5])

[[{'label': 'neutral', 'score': 0.7419658303260803},
  {'label': 'realization', 'score': 0.1369493156671524},
  {'label': 'approval', 'score': 0.09110077470541},
  {'label': 'disappointment', 'score': 0.022280389443039894},
  {'label': 'annoyance', 'score': 0.015249023213982582},
  {'label': 'admiration', 'score': 0.013294525444507599},
  {'label': 'disapproval', 'score': 0.011003623716533184},
  {'label': 'sadness', 'score': 0.008263121359050274},
  {'label': 'disgust', 'score': 0.003915111999958754},
  {'label': 'optimism', 'score': 0.003352390369400382},
  {'label': 'confusion', 'score': 0.002450305037200451},
  {'label': 'fear', 'score': 0.0018813037313520908},
  {'label': 'embarrassment', 'score': 0.0016917991451919079},
  {'label': 'anger', 'score': 0.0015422748401761055},
  {'label': 'surprise', 'score': 0.001458858954720199},
  {'label': 'relief', 'score': 0.0010335136903449893},
  {'label': 'love', 'score': 0.0010275793028995395},
  {'label': 'desire', 'score': 0.0009544233907945454},
  {'label': 'pride', 'score': 0.0009494287660345435},
  {'label': 'gratitude', 'score': 0.0009397930116392672},
  {'label': 'amusement', 'score': 0.0009305354906246066},
  {'label': 'grief', 'score': 0.0008550973143428564},
  {'label': 'joy', 'score': 0.0007814092678017914},
  {'label': 'excitement', 'score': 0.0006550798425450921},
  {'label': 'curiosity', 'score': 0.0006436316180042922},
  {'label': 'remorse', 'score': 0.0006408243207260966},
  {'label': 'caring', 'score': 0.000638169702142477},
  {'label': 'nervousness', 'score': 0.0005737869651056826}]]

In [5]:
sentences = books["description"][0].split(".")
predictions = classifier(sentences)

In [6]:
sentences[0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives'

In [7]:
predictions[0]

[{'label': 'excitement', 'score': 0.49505096673965454},
 {'label': 'admiration', 'score': 0.2984217405319214},
 {'label': 'neutral', 'score': 0.11334912478923798},
 {'label': 'approval', 'score': 0.06156667321920395},
 {'label': 'surprise', 'score': 0.025452638044953346},
 {'label': 'curiosity', 'score': 0.020611191168427467},
 {'label': 'joy', 'score': 0.013649091124534607},
 {'label': 'love', 'score': 0.012229576706886292},
 {'label': 'desire', 'score': 0.012063363566994667},
 {'label': 'optimism', 'score': 0.005851102992892265},
 {'label': 'realization', 'score': 0.004697068128734827},
 {'label': 'annoyance', 'score': 0.0029893338214606047},
 {'label': 'pride', 'score': 0.002599795116111636},
 {'label': 'confusion', 'score': 0.0024072828236967325},
 {'label': 'amusement', 'score': 0.0021955508273094893},
 {'label': 'disapproval', 'score': 0.0021141988690942526},
 {'label': 'disappointment', 'score': 0.001981467939913273},
 {'label': 'disgust', 'score': 0.001436283579096198},
 {'label': 'fear', 'score': 0.001415332080796361},
 {'label': 'anger', 'score': 0.0012881984002888203},
 {'label': 'caring', 'score': 0.001193404896184802},
 {'label': 'sadness', 'score': 0.0011692814296111465},
 {'label': 'gratitude', 'score': 0.0008985294844023883},
 {'label': 'relief', 'score': 0.0008879504748620093},
 {'label': 'nervousness', 'score': 0.0006956652505323291},
 {'label': 'embarrassment', 'score': 0.0004494803724810481},
 {'label': 'grief', 'score': 0.0004383956256788224},
 {'label': 'remorse', 'score': 0.00024301867233589292}]

In [8]:
sentences[3]

' Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist'

In [9]:
predictions[3]

[{'label': 'neutral', 'score': 0.9423109889030457},
 {'label': 'approval', 'score': 0.03423655033111572},
 {'label': 'realization', 'score': 0.024165352806448936},
 {'label': 'annoyance', 'score': 0.006766472011804581},
 {'label': 'admiration', 'score': 0.005985408555716276},
 {'label': 'sadness', 'score': 0.005476201884448528},
 {'label': 'disappointment', 'score': 0.004732154309749603},
 {'label': 'optimism', 'score': 0.003723397385329008},
 {'label': 'disapproval', 'score': 0.003488865913823247},
 {'label': 'disgust', 'score': 0.002289121737703681},
 {'label': 'fear', 'score': 0.0019254954531788826},
 {'label': 'anger', 'score': 0.001611347426660359},
 {'label': 'confusion', 'score': 0.0015487552154809237},
 {'label': 'desire', 'score': 0.0014074408682063222},
 {'label': 'caring', 'score': 0.0013327669585123658},
 {'label': 'amusement', 'score': 0.0012335135834291577},
 {'label': 'joy', 'score': 0.0011541954008862376},
 {'label': 'gratitude', 'score': 0.001131444820202887},
 {'label': 'excitement', 'score': 0.0009034085087478161},
 {'label': 'curiosity', 'score': 0.0008207091013900936},
 {'label': 'love', 'score': 0.0008027018047869205},
 {'label': 'surprise', 'score': 0.0007140403031371534},
 {'label': 'grief', 'score': 0.0007081418880261481},
 {'label': 'embarrassment', 'score': 0.0006961370818316936},
 {'label': 'relief', 'score': 0.0006308684824034572},
 {'label': 'pride', 'score': 0.0006148199317976832},
 {'label': 'remorse', 'score': 0.0005936583620496094},
 {'label': 'nervousness', 'score': 0.00043113288120366633}]

In [10]:
predictions

[[{'label': 'excitement', 'score': 0.49505096673965454},
  {'label': 'admiration', 'score': 0.2984217405319214},
  {'label': 'neutral', 'score': 0.11334912478923798},
  {'label': 'approval', 'score': 0.06156667321920395},
  {'label': 'surprise', 'score': 0.025452638044953346},
  {'label': 'curiosity', 'score': 0.020611191168427467},
  {'label': 'joy', 'score': 0.013649091124534607},
  {'label': 'love', 'score': 0.012229576706886292},
  {'label': 'desire', 'score': 0.012063363566994667},
  {'label': 'optimism', 'score': 0.005851102992892265},
  {'label': 'realization', 'score': 0.004697068128734827},
  {'label': 'annoyance', 'score': 0.0029893338214606047},
  {'label': 'pride', 'score': 0.002599795116111636},
  {'label': 'confusion', 'score': 0.0024072828236967325},
  {'label': 'amusement', 'score': 0.0021955508273094893},
  {'label': 'disapproval', 'score': 0.0021141988690942526},
  {'label': 'disappointment', 'score': 0.001981467939913273},
  {'label': 'disgust', 'score': 0.001436283579096198},
  {'label': 'fear', 'score': 0.001415332080796361},
  {'label': 'anger', 'score': 0.0012881984002888203},
  {'label': 'caring', 'score': 0.001193404896184802},
  {'label': 'sadness', 'score': 0.0011692814296111465},
  {'label': 'gratitude', 'score': 0.0008985294844023883},
  {'label': 'relief', 'score': 0.0008879504748620093},
  {'label': 'nervousness', 'score': 0.0006956652505323291},
  {'label': 'embarrassment', 'score': 0.0004494803724810481},
  {'label': 'grief', 'score': 0.0004383956256788224},
  {'label': 'remorse', 'score': 0.00024301867233589292}],
 [{'label': 'neutral', 'score': 0.9304519891738892},
  {'label': 'approval', 'score': 0.03257761523127556},
  {'label': 'realization', 'score': 0.012696177698671818},
  {'label': 'admiration', 'score': 0.009453460574150085},
  {'label': 'annoyance', 'score': 0.0062142591923475266},
  {'label': 'disapproval', 'score': 0.0029011417645961046},
  {'label': 'disappointment', 'score': 0.0026528954040259123},
  {'label': 'optimism', 'score': 0.0019252232741564512},
  {'label': 'amusement', 'score': 0.0017451054882258177},
  {'label': 'disgust', 'score': 0.0016568998107686639},
  {'label': 'confusion', 'score': 0.0016196835786104202},
  {'label': 'sadness', 'score': 0.0014964545844122767},
  {'label': 'anger', 'score': 0.0014913140330463648},
  {'label': 'joy', 'score': 0.0013627627631649375},
  {'label': 'excitement', 'score': 0.0010866278316825628},
  {'label': 'gratitude', 'score': 0.0009999164612963796},
  {'label': 'love', 'score': 0.0009145570220425725},
  {'label': 'fear', 'score': 0.0008080743718892336},
  {'label': 'curiosity', 'score': 0.0007418837049044669},
  {'label': 'surprise', 'score': 0.0006469791405834258},
  {'label': 'caring', 'score': 0.0006131515838205814},
  {'label': 'desire', 'score': 0.0004939798964187503},
  {'label': 'pride', 'score': 0.0004914430319331586},
  {'label': 'embarrassment', 'score': 0.0004754802503157407},
  {'label': 'relief', 'score': 0.0003834906092379242},
  {'label': 'remorse', 'score': 0.0002674511924851686},
  {'label': 'grief', 'score': 0.0002609100774861872},
  {'label': 'nervousness', 'score': 0.00018528827058617026}],
 [{'label': 'neutral', 'score': 0.9456536769866943},
  {'label': 'realization', 'score': 0.030264215543866158},
  {'label': 'approval', 'score': 0.022307073697447777},
  {'label': 'sadness', 'score': 0.008609021082520485},
  {'label': 'disappointment', 'score': 0.008574116043746471},
  {'label': 'disapproval', 'score': 0.0064414492808282375},
  {'label': 'annoyance', 'score': 0.00567382900044322},
  {'label': 'optimism', 'score': 0.003350453684106469},
  {'label': 'admiration', 'score': 0.0029649846255779266},
  {'label': 'confusion', 'score': 0.0022469523828476667},
  {'label': 'joy', 'score': 0.001931511564180255},
  {'label': 'fear', 'score': 0.0017752166604623199},
  {'label': 'amusement', 'score': 0.0016993095632642508},
  {'label': 'disgust', 'score': 0.001639123889617622},
  {'label': 'caring', 'score': 0.0015369150787591934},
  {'label': 'gratitude', 'score': 0.0014884901465848088},
  {'label': 'desire', 'score': 0.0014817937044426799},
  {'label': 'excitement', 'score': 0.0010602932889014482},
  {'label': 'anger', 'score': 0.0010424380889162421},
  {'label': 'relief', 'score': 0.0010348408250138164},
  {'label': 'love', 'score': 0.0010253505315631628},
  {'label': 'surprise', 'score': 0.0009858706034719944},
  {'label': 'embarrassment', 'score': 0.0009728071163408458},
  {'label': 'grief', 'score': 0.0009689618600532413},
  {'label': 'remorse', 'score': 0.0009397817775607109},
  {'label': 'curiosity', 'score': 0.0008562374860048294},
  {'label': 'nervousness', 'score': 0.0006771051557734609},
  {'label': 'pride', 'score': 0.0005158293060958385}],
 [{'label': 'neutral', 'score': 0.9423109889030457},
  {'label': 'approval', 'score': 0.03423655033111572},
  {'label': 'realization', 'score': 0.024165352806448936},
  {'label': 'annoyance', 'score': 0.006766472011804581},
  {'label': 'admiration', 'score': 0.005985408555716276},
  {'label': 'sadness', 'score': 0.005476201884448528},
  {'label': 'disappointment', 'score': 0.004732154309749603},
  {'label': 'optimism', 'score': 0.003723397385329008},
  {'label': 'disapproval', 'score': 0.003488865913823247},
  {'label': 'disgust', 'score': 0.002289121737703681},
  {'label': 'fear', 'score': 0.0019254954531788826},
  {'label': 'anger', 'score': 0.001611347426660359},
  {'label': 'confusion', 'score': 0.0015487552154809237},
  {'label': 'desire', 'score': 0.0014074408682063222},
  {'label': 'caring', 'score': 0.0013327669585123658},
  {'label': 'amusement', 'score': 0.0012335135834291577},
  {'label': 'joy', 'score': 0.0011541954008862376},
  {'label': 'gratitude', 'score': 0.001131444820202887},
  {'label': 'excitement', 'score': 0.0009034085087478161},
  {'label': 'curiosity', 'score': 0.0008207091013900936},
  {'label': 'love', 'score': 0.0008027018047869205},
  {'label': 'surprise', 'score': 0.0007140403031371534},
  {'label': 'grief', 'score': 0.0007081418880261481},
  {'label': 'embarrassment', 'score': 0.0006961370818316936},
  {'label': 'relief', 'score': 0.0006308684824034572},
  {'label': 'pride', 'score': 0.0006148199317976832},
  {'label': 'remorse', 'score': 0.0005936583620496094},
  {'label': 'nervousness', 'score': 0.00043113288120366633}],
 [{'label': 'sadness', 'score': 0.7170385122299194},
  {'label': 'neutral', 'score': 0.22705116868019104},
  {'label': 'disappointment', 'score': 0.03747539967298508},
  {'label': 'caring', 'score': 0.035510994493961334},
  {'label': 'grief', 'score': 0.02281017042696476},
  {'label': 'remorse', 'score': 0.022793488577008247},
  {'label': 'approval', 'score': 0.021102702245116234},
  {'label': 'realization', 'score': 0.020856240764260292},
  {'label': 'nervousness', 'score': 0.009491332806646824},
  {'label': 'desire', 'score': 0.007585044018924236},
  {'label': 'annoyance', 'score': 0.007165505550801754},
  {'label': 'fear', 'score': 0.005749265197664499},
  {'label': 'love', 'score': 0.0049141934141516685},
  {'label': 'disapproval', 'score': 0.004410542547702789},
  {'label': 'joy', 'score': 0.004319217521697283},
  {'label': 'admiration', 'score': 0.004266396630555391},
  {'label': 'optimism', 'score': 0.003972637467086315},
  {'label': 'relief', 'score': 0.0038718769792467356},
  {'label': 'disgust', 'score': 0.0027551883831620216},
  {'label': 'anger', 'score': 0.002716469345614314},
  {'label': 'embarrassment', 'score': 0.002129610162228346},
  {'label': 'confusion', 'score': 0.0019996785558760166},
  {'label': 'amusement', 'score': 0.001811110763810575},
  {'label': 'curiosity', 'score': 0.0015943964244797826},
  {'label': 'gratitude', 'score': 0.0015786235453560948},
  {'label': 'excitement', 'score': 0.001214152667671442},
  {'label': 'surprise', 'score': 0.000948586966842413},
  {'label': 'pride', 'score': 0.0008664464694447815}],
 [{'label': 'joy', 'score': 0.7413578033447266},
  {'label': 'admiration', 'score': 0.17403587698936462},
  {'label': 'approval', 'score': 0.09558115899562836},
  {'label': 'neutral', 'score': 0.07788758724927902},
  {'label': 'excitement', 'score': 0.049850936979055405},
  {'label': 'amusement', 'score': 0.027041487395763397},
  {'label': 'pride', 'score': 0.01838814653456211},
  {'label': 'relief', 'score': 0.017696542665362358},
  {'label': 'love', 'score': 0.01233508437871933},
  {'label': 'annoyance', 'score': 0.01139634009450674},
  {'label': 'realization', 'score': 0.00999884307384491},
  {'label': 'optimism', 'score': 0.0087283281609416},
  {'label': 'caring', 'score': 0.006444074679166079},
  {'label': 'disapproval', 'score': 0.003990005701780319},
  {'label': 'disappointment', 'score': 0.003481767838820815},
  {'label': 'gratitude', 'score': 0.003122167196124792},
  {'label': 'desire', 'score': 0.002751909662038088},
  {'label': 'anger', 'score': 0.002405561273917556},
  {'label': 'sadness', 'score': 0.002400920959189534},
  {'label': 'surprise', 'score': 0.0015793474158272147},
  {'label': 'nervousness', 'score': 0.0010802648030221462},
  {'label': 'grief', 'score': 0.0009937358554452658},
  {'label': 'embarrassment', 'score': 0.0009483303292654455},
  {'label': 'disgust', 'score': 0.0009137504966929555},
  {'label': 'curiosity', 'score': 0.0008255874854512513},
  {'label': 'confusion', 'score': 0.0008174809045158327},
  {'label': 'fear', 'score': 0.0006173045258037746},
  {'label': 'remorse', 'score': 0.0003333486965857446}],
 [{'label': 'admiration', 'score': 0.6923784613609314},
  {'label': 'neutral', 'score': 0.17593812942504883},
  {'label': 'approval', 'score': 0.16847185790538788},
  {'label': 'excitement', 'score': 0.03926482051610947},
  {'label': 'surprise', 'score': 0.008807428181171417},
  {'label': 'realization', 'score': 0.00839808490127325},
  {'label': 'optimism', 'score': 0.007704562041908503},
  {'label': 'pride', 'score': 0.0048834774643182755},
  {'label': 'joy', 'score': 0.00467676343396306},
  {'label': 'annoyance', 'score': 0.003625584999099374},
  {'label': 'curiosity', 'score': 0.0033035380765795708},
  {'label': 'love', 'score': 0.0031879900489002466},
  {'label': 'disapproval', 'score': 0.002368832705542445},
  {'label': 'disappointment', 'score': 0.002074734540656209},
  {'label': 'confusion', 'score': 0.0016575624467805028},
  {'label': 'gratitude', 'score': 0.0015371954068541527},
  {'label': 'desire', 'score': 0.0013163558905944228},
  {'label': 'amusement', 'score': 0.0012664987007156014},
  {'label': 'anger', 'score': 0.0009398529655300081},
  {'label': 'caring', 'score': 0.0008626258932054043},
  {'label': 'disgust', 'score': 0.0006821208517067134},
  {'label': 'relief', 'score': 0.000672634516377002},
  {'label': 'fear', 'score': 0.0005614982801489532},
  {'label': 'sadness', 'score': 0.0004433481371961534},
  {'label': 'embarrassment', 'score': 0.00031752846552990377},
  {'label': 'grief', 'score': 0.0002563344605732709},
  {'label': 'nervousness', 'score': 0.0001776309363776818},
  {'label': 'remorse', 'score': 0.00016375284758396447}],
 [{'label': 'neutral', 'score': 0.9549601674079895},
  {'label': 'approval', 'score': 0.022920329123735428},
  {'label': 'disapproval', 'score': 0.009044047445058823},
  {'label': 'realization', 'score': 0.008665136992931366},
  {'label': 'annoyance', 'score': 0.006453515030443668},
  {'label': 'disappointment', 'score': 0.0055939024314284325},
  {'label': 'admiration', 'score': 0.004978002514690161},
  {'label': 'sadness', 'score': 0.0023011553566902876},
  {'label': 'optimism', 'score': 0.002142632380127907},
  {'label': 'confusion', 'score': 0.002089390531182289},
  {'label': 'excitement', 'score': 0.0019051306881010532},
  {'label': 'joy', 'score': 0.0016943644732236862},
  {'label': 'anger', 'score': 0.0015344716375693679},
  {'label': 'disgust', 'score': 0.0014689203817397356},
  {'label': 'gratitude', 'score': 0.001370571437291801},
  {'label': 'amusement', 'score': 0.001089825527742505},
  {'label': 'fear', 'score': 0.0010508567793294787},
  {'label': 'desire', 'score': 0.0010161622194573283},
  {'label': 'curiosity', 'score': 0.000984524143859744},
  {'label': 'surprise', 'score': 0.0009003463201224804},
  {'label': 'love', 'score': 0.0008973359945230186},
  {'label': 'caring', 'score': 0.0008596849511377513},
  {'label': 'embarrassment', 'score': 0.0006433893577195704},
  {'label': 'relief', 'score': 0.0005002192920073867},
  {'label': 'pride', 'score': 0.0004335329285822809},
  {'label': 'remorse', 'score': 0.000402823236072436},
  {'label': 'grief', 'score': 0.00039013518835417926},
  {'label': 'nervousness', 'score': 0.00035462036612443626}]]

In [11]:
sorted(predictions[0],key=lambda x:x["label"])

[{'label': 'admiration', 'score': 0.2984217405319214},
 {'label': 'amusement', 'score': 0.0021955508273094893},
 {'label': 'anger', 'score': 0.0012881984002888203},
 {'label': 'annoyance', 'score': 0.0029893338214606047},
 {'label': 'approval', 'score': 0.06156667321920395},
 {'label': 'caring', 'score': 0.001193404896184802},
 {'label': 'confusion', 'score': 0.0024072828236967325},
 {'label': 'curiosity', 'score': 0.020611191168427467},
 {'label': 'desire', 'score': 0.012063363566994667},
 {'label': 'disappointment', 'score': 0.001981467939913273},
 {'label': 'disapproval', 'score': 0.0021141988690942526},
 {'label': 'disgust', 'score': 0.001436283579096198},
 {'label': 'embarrassment', 'score': 0.0004494803724810481},
 {'label': 'excitement', 'score': 0.49505096673965454},
 {'label': 'fear', 'score': 0.001415332080796361},
 {'label': 'gratitude', 'score': 0.0008985294844023883},
 {'label': 'grief', 'score': 0.0004383956256788224},
 {'label': 'joy', 'score': 0.013649091124534607},
 {'label': 'love', 'score': 0.012229576706886292},
 {'label': 'nervousness', 'score': 0.0006956652505323291},
 {'label': 'neutral', 'score': 0.11334912478923798},
 {'label': 'optimism', 'score': 0.005851102992892265},
 {'label': 'pride', 'score': 0.002599795116111636},
 {'label': 'realization', 'score': 0.004697068128734827},
 {'label': 'relief', 'score': 0.0008879504748620093},
 {'label': 'remorse', 'score': 0.00024301867233589292},
 {'label': 'sadness', 'score': 0.0011692814296111465},
 {'label': 'surprise', 'score': 0.025452638044953346}]

In [12]:
import numpy as np
emotion_labels = ["anger","disgust","fear","joy","neutral","sadness","surprise","neutral"]
isbn = []
emotion_scores = {label:[] for label in emotion_labels}

def calculate_max_emotion_scores(predictions):
        per_emotion_scores = {label:[] for label in emotion_labels}
        for prediction in predictions:
                sorted_predictions = sorted(prediction, key=lambda x: x["label"])
                for index , label in enumerate(emotion_labels):
                        per_emotion_scores[label].append(sorted_predictions[index]["score"])
                return {label: np.max(scores) for label,scores in per_emotion_scores.items()}

In [13]:
for i in range (10):
        isbn.append(books["isbn13"][i])
        sentences = books["description"][i].split(".")
        predictions = classifier(sentences)
        max_scores = calculate_max_emotion_scores(predictions)
        for label in emotion_labels:
                emotion_scores[label].append(max_scores[label])

In [14]:
emotion_scores

{'anger': [np.float64(0.2984217405319214),
  np.float64(0.842938244342804),
  np.float64(0.8438476920127869),
  np.float64(0.009910427033901215),
  np.float64(0.001369174919091165),
  np.float64(0.01607685349881649),
  np.float64(0.8295944929122925),
  np.float64(0.934485912322998),
  np.float64(0.13989201188087463),
  np.float64(0.0031212291214615107)],
 'disgust': [np.float64(0.0021955508273094893),
  np.float64(0.0008654151461087167),
  np.float64(0.0005711785051971674),
  np.float64(0.0010734617244452238),
  np.float64(0.0024822058621793985),
  np.float64(0.0019459299510344863),
  np.float64(0.0005306174862198532),
  np.float64(0.0007446648669429123),
  np.float64(0.0011058931704610586),
  np.float64(0.0025026702787727118)],
 'fear': [np.float64(0.0012881984002888203),
  np.float64(0.0007592067122459412),
  np.float64(0.04729536175727844),
  np.float64(0.0018201866187155247),
  np.float64(0.002586043905466795),
  np.float64(0.0005513182259164751),
  np.float64(0.0011632367968559265),
  np.float64(0.002159816212952137),
  np.float64(0.0011445458512753248),
  np.float64(0.004458622541278601)],
 'joy': [np.float64(0.0029893338214606047),
  np.float64(0.003019497962668538),
  np.float64(0.037731606513261795),
  np.float64(0.004106419626623392),
  np.float64(0.011019352823495865),
  np.float64(0.0047540804371237755),
  np.float64(0.004767222795635462),
  np.float64(0.005288686137646437),
  np.float64(0.005653133615851402),
  np.float64(0.016172753646969795)],
 'neutral': [np.float64(0.06156667321920395),
  np.float64(0.06156667321920395),
  np.float64(0.06941205263137817),
  np.float64(0.06941205263137817),
  np.float64(0.06753169000148773),
  np.float64(0.06753169000148773),
  np.float64(0.17768625915050507),
  np.float64(0.17768625915050507),
  np.float64(0.016053330153226852),
  np.float64(0.016053330153226852),
  np.float64(0.08671567589044571),
  np.float64(0.08671567589044571),
  np.float64(0.10308253765106201),
  np.float64(0.10308253765106201),
  np.float64(0.05853123217821121),
  np.float64(0.05853123217821121),
  np.float64(0.262891560792923),
  np.float64(0.262891560792923),
  np.float64(0.010169359855353832),
  np.float64(0.010169359855353832)],
 'sadness': [np.float64(0.001193404896184802),
  np.float64(0.0009462106972932816),
  np.float64(0.005412074271589518),
  np.float64(0.0023142562713474035),
  np.float64(0.0023548074532300234),
  np.float64(0.0003168867260683328),
  np.float64(0.00174351641908288),
  np.float64(0.0018905046163126826),
  np.float64(0.0013133047614246607),
  np.float64(0.0012086855713278055)],
 'surprise': [np.float64(0.0024072828236967325),
  np.float64(0.0008778040646575391),
  np.float64(0.002649332396686077),
  np.float64(0.004594969097524881),
  np.float64(0.0018010555068030953),
  np.float64(0.009557385928928852),
  np.float64(0.0011497423984110355),
  np.float64(0.0017568013863638043),
  np.float64(0.0005370019935071468),
  np.float64(0.001407233881764114)]}

In [15]:
from tqdm import tqdm
emotion_labels = ["anger","disgust","fear","joy","sadness","surprise","neutral"]
isbn = []
emotion_scores = {label:[] for label in emotion_labels}
for i in tqdm(range(len(books))):
        isbn.append(books["isbn13"][i])
        sentences = books["description"][i].split(".")
        predictions = classifier(sentences)
        max_scores = calculate_max_emotion_scores(predictions)
        for label in emotion_labels:
                emotion_scores[label].append(max_scores[label])

100%|██████████| 6144/6144 [13:55<00:00,  7.35it/s]

In [16]:
emotions_df = pd.DataFrame(emotion_scores)
emotions_df["isbn13"] = isbn

In [18]:
emotions_df

,anger,disgust,fear,joy,sadness,surprise,neutral,isbn13
0,0.298422,0.002196,0.001288,0.002989,0.061567,0.001193,0.002407,9780002005883
1,0.842938,0.000865,0.000759,0.003019,0.069412,0.000946,0.000878,9780002261982
2,0.843848,0.000571,0.047295,0.037732,0.067532,0.005412,0.002649,9780006178736
3,0.009910,0.001073,0.001820,0.004106,0.177686,0.002314,0.004595,9780006280897
4,0.001369,0.002482,0.002586,0.011019,0.016053,0.002355,0.001801,9780006280934
...,...,...,...,...,...,...,...,...
6139,0.918175,0.002467,0.000940,0.002384,0.068051,0.001374,0.001620,9788173031014
6140,0.413401,0.003701,0.001166,0.003801,0.252189,0.040689,0.001396,9788179921623
6141,0.821012,0.000477,0.001257,0.004982,0.158923,0.004406,0.001251,9788185300535
6142,0.342617,0.000475,0.000438,0.002393,0.473998,0.005641,0.002093,9789027712059
6143,0.846255,0.003099,0.001774,0.003541,0.044227,0.006023,0.001088,9789042003408

In [19]:
books = pd.merge(books,emotions_df, on = "isbn13")

In [20]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,...,title_and_subtitle,tagged_description,simple_categories,anger,disgust,fear,joy,sadness,surprise,neutral
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,...,Gilead,9780002005883 A NOVEL THAT READERS and critic...,Fiction,0.298422,0.002196,0.001288,0.002989,0.061567,0.001193,0.002407
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,Spider's Web - A Novel,9780002261982 A new 'Christie for Christmas' ...,Fiction,0.842938,0.000865,0.000759,0.003019,0.069412,0.000946,0.000878
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,...,Rage of angels,"9780006178736 A memorable, mesmerizing heroin...",Fiction,0.843848,0.000571,0.047295,0.037732,0.067532,0.005412,0.002649
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,...,The Four Loves,9780006280897 Lewis' work on the nature of lo...,Nonfiction,0.009910,0.001073,0.001820,0.004106,0.177686,0.002314,0.004595
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,...,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. L...",Nonfiction,0.001369,0.002482,0.002586,0.011019,0.016053,0.002355,0.001801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6139,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,...,Journey to the East,9788173031014 This book tells the tale of a m...,Nonfiction,0.918175,0.002467,0.000940,0.002384,0.068051,0.001374,0.001620
6140,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,...,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Pass...,Fiction,0.413401,0.003701,0.001166,0.003801,0.252189,0.040689,0.001396
6141,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,...,I Am that - Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless...,Nonfiction,0.821012,0.000477,0.001257,0.004982,0.158923,0.004406,0.001251
6142,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,...,The Berlin Phenomenology,9789027712059 Since the three volume edition ...,Nonfiction,0.342617,0.000475,0.000438,0.002393,0.473998,0.005641,0.002093
6143,9789042003408,9042003405,'I'm Telling You Stories',Helena Grice;Tim Woods,Literary Criticism,http://books.google.com/books/content?id=2lVyR...,This is a jubilant and rewarding collection of...,1998.0,3.70,136.0,...,'I'm Telling You Stories' - Jeanette Winterson...,9789042003408 This is a jubilant and rewardin...,Nonfiction,0.846255,0.003099,0.001774,0.003541,0.044227,0.006023,0.001088

In [21]:
books.to_csv("books_with_emotions.csv",index=False)